---
title: "Intégrales généralisées"
about:
  template: jolla
  links:
    - icon: twitter
      text: Twitter
      href: https://twitter.com
    - icon: linkedin
      text: LinkedIn
      href: https://linkedin.com
    - icon: github
      text: Github
      href: https://github.com
---

### Exemples fondamentaux

Nous présentons deux exemples fondamentaux auxquels on se ramène très souvent pour étudier la convergence d’une intégrale généralisée.

#### Intégrales de Riemann

::: exercise-box
**Théorème 1**

1.  La fonction $t \mapsto \frac{1}{t^\alpha}$ a une intégrale convergente sur $[1, +\infty[$ si et seulement si $\alpha > 1$.
2.  La fonction $t \mapsto \frac{1}{t^\alpha}$ a une intégrale convergente sur $]0, 1]$ si et seulement si $\alpha < 1$.

<details>

<summary><strong>Démonstration</strong></summary>

On a : $$ \int_{1}^{x} \frac{dt}{t^\alpha} = 
\begin{cases} 
\frac{1}{\alpha-1}(1 - x^{1-\alpha}), & \text{si } \alpha \neq 1 \\ 
\ln(x), & \text{si } \alpha = 1 
\end{cases} $$

Ainsi, cette intégrale admet une limite finie en $+\infty$ si et seulement si $\alpha > 1$.

De même, on a : $$ \int_{x}^{1} \frac{dt}{t^\alpha} = 
\begin{cases} 
\frac{1}{1-\alpha}(1 - x^{1-\alpha}), & \text{si } \alpha \neq 1 \\ 
-\ln(x), & \text{si } \alpha = 1 
\end{cases} $$

Cette intégrale admet une limite finie en 0 si et seulement si $\alpha < 1$.

Ce résultat implique directement le suivant. Soit $a < b$ deux réels. Alors on a : $$ \int_{a}^{b} \frac{dt}{(b - t)^\alpha} < +\infty \iff \alpha < 1. $$

</details>
:::

</div>

<!-- Fermeture de la div à la ligne 47 -->

#### Intégrales de Bertrand

::: exercise-box
**Théorème 2**

1.  La fonction $t \mapsto \frac{1}{t^\alpha \ln(t)^\beta}$ a une intégrale convergente sur $[e, +\infty[$ si et seulement si $\alpha > 1$ ou $\alpha = 1$ et $\beta > 1$.
2.  La fonction $t \mapsto \frac{1}{t^\alpha |\ln(t)|^\beta}$ a une intégrale convergente sur $]0, \frac{1}{e}]$ si et seulement si $\alpha < 1$ ou $\alpha = 1$ et $\beta > 1$.

<details>

<summary><strong>Démonstration</strong></summary>

Montrons (i). Si $\alpha > 1$, alors il existe $\gamma > 0$ tel que $1 < \gamma < \alpha$. On a alors : $$ \frac{1}{t^\alpha (\ln t)^\beta} = o \left( \frac{1}{t^\gamma} \right), $$ et donc la fonction $t \mapsto \frac{1}{t^\alpha (\ln t)^\beta}$ a une intégrale convergente sur $[e, +\infty[$.

Si $\alpha = 1$, posons $u = \ln t$. Alors pour $x \in [e, +\infty[$ on a : $$ \int_{e}^{x} \frac{dt}{t (\ln t)^\beta} = \int_{1}^{\ln x} \frac{du}{u^\beta} = 
\begin{cases} 
\frac{1}{\beta - 1} (1 - (\ln x)^{1-\beta}), & \text{si } \beta \neq 1 \\ 
\ln (\ln x), & \text{si } \beta = 1 
\end{cases} $$

D’où le résultat.

Montrons (ii). Supposons $\alpha < 1$. Alors pour $\gamma$ tel que $\alpha < \gamma < 1$, on a : $$ \frac{1}{t^\alpha |\ln t|^\beta} = o \left( \frac{1}{t^\gamma} \right), $$ d’où le résultat étant donné que l’intégrale sur $[0, 1]$ de la fonction $t \mapsto \frac{1}{t^\gamma}$ est convergente.

De même que pour le cas (i), on trouve : $$ \int_{e}^{1} \frac{dt}{t |\ln t|^\beta} = \int_{-\ln x}^{1} \frac{du}{| u |^\beta}, $$ d’où le résultat.

</details>
:::

</div>

<!-- Fermeture de la div à la ligne 81 -->

### Exercices

::: exercise-box
**Exercice 1**

Étudier la convergence de l’intégrale $$\int_{0}^{1} \frac{dx}{x^u (1-x)^{1-u}}$$ en fonction du paramètre $u$.

<details>

<summary><strong>Corrigé</strong></summary>

<!-- Corrigé de l'exercice ici -->

Indication

</details>
:::

</div>

<!-- Fermeture de la div à la ligne 97 -->

::: exercise-box
**Exercice 2**

1.  Soient $\alpha \in \mathbb{R}$ et $\beta \in \mathbb{R}$. Déterminer l'ensemble des couples $(\alpha, \beta)$ pour lesquels l'intégrale généralisée $$\int_{0}^{+\infty} \frac{t^{\alpha}}{1+t^{\beta}}dt$$ est convergente.

2.  Soit $f$ une fonction intégrable sur tout intervalle borné de $\mathbb{R}$ telle que : $$ \lim_{t \to +\infty} f(t)=l \quad \text{et} \quad \lim_{t \to -\infty}=l'$$ Calculer $$\int_{-\infty}^{+\infty}(f(t+1)-f(t)) dt$$

<details>

<summary><strong>Corrigé</strong></summary>

<!-- Corrigé de l'exercice ici -->

Indication

</details>

</div>

<!-- Fermeture de la div à la ligne 183 -->
:::
